OVCHEGRAM/Controllers/MEController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using OVCHEGRAM.DBModels;
using OVCHEGRAM.Models;
using OVCHEGRAM.Repositories;
using OVCHEGRAM.Extensions;

namespace OVCHEGRAM.Controllers;

[Authorize]
public class MEController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly UserRepository _userRepository;
    private readonly ConversationRepository _conversationRepository;
    private readonly FileRepository _fileRepository;

    public MEController(ILogger<HomeController> logger, UserRepository userRepository,
        ConversationRepository conversationRepository,
        FileRepository fileRepository)
    {
        _logger = logger;
        _userRepository = userRepository;
        _conversationRepository = conversationRepository;
        _fileRepository = fileRepository;
    }

    public async Task<IActionResult> Profile(int id)
    {
        var user = await _userRepository.GetByIdAsync(id);
        if (user == null) return Forbid();
        var isAllowed = id == User.GetUserId();
        return View((await Converter.ConvertToProfileModel(user), isAllowed));
    }
    
    [HttpGet]
    public async Task<IActionResult> Users()
    {
        var users = await _userRepository.GetPageAsync();
        var use = await Task.WhenAll(users.Select(Converter.ConvertToProfileModel));
        return View(use);
    }
    
    [HttpGet]
    public async Task<IActionResult> Conversations()
    {
        var conversations = await _conversationRepository.GetUsersLastConservationsDataAsync(User.GetUserId());
        foreach (var conversation in conversations)
        {
            conversation.LastMessageContent ??= "File";
            if (conversation.LastMessageContent.Length > 30)
                conversation.LastMessageContent = conversation.LastMessageContent[..30] + "...";
            conversation.ConversationPictureName =
                await _fileRepository.GetFilePathByIdAsync(conversation.ConversationPictureId);
        }

        return View(conversations);
    }

    [HttpPost]
    public async Task<IActionResult> ChangeProfile(UserProfileModel newUserProfile)
    {
        var userId = User.GetUserId();
        var user = await _userRepository.GetByIdAsync(userId);
        if (user == null) return Forbid();
        user.FirstName = newUserProfile.FirstName;
        user.SecondName = newUserProfile.SecondName;
        user.Gender = newUserProfile.Gender;
        user.Town = newUserProfile.Town;
        if (newUserProfile.File != null)
        {
            var fileId = _fileRepository.UploadFileAsync(newUserProfile.File);
            user.ProfilePicId = await fileId;
        }

        await _userRepository.UpdateAsync(user);
        return RedirectToAction("Profile", new { id = user.Id });
    }

    public async Task<IActionResult> LogOut()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToRoute(new { controller = "Home", action = "Index" });
    }

    [HttpPost]
    public async Task<IActionResult> CreateGroupChat(string groupTitle, IFormFile file, IEnumerable<int> userIds)
    {
        int? fileId = null;
        if (file != null)
            fileId = await _fileRepository.UploadFileAsync(file);
        var conversationId =
            await _conversationRepository.CreateGroupChatAsync(userIds.ToList(), groupTitle,
                User.GetUserId(), fileId);
        return Ok(new { redirectUrl = Url.Action("Conversation", "Message", new { conversationId }) });
    }

    public async Task<IActionResult> GetUsersHtml(int page = 1, string filter = "", int pageSize = 10)
    {
        var nextItemsTasks = await GetUsers(page, filter, pageSize);
        var nextItems = await Task.WhenAll(nextItemsTasks.Select(Converter.ConvertToProfileModel));
        return PartialView("_PartialUsers", nextItems);
    }

    public async Task<IActionResult> GetUsersNamesHtml(int page = 1, string filter = "", int pageSize = 10)
    {
        var nextItemsTasks = await GetUsers(page, filter, pageSize);
        var nextItems = await Task.WhenAll(nextItemsTasks.Select(Converter.ConvertToProfileModel));
        return PartialView("_PartialUsersNames", nextItems);
    }

    public async Task<IActionResult> RedirectToPersonalConversation(int id1)
    {
        var userId = User.GetUserId();
        var conversationId = await _conversationRepository.GetByUsersIdAsync(id1, userId);
        if (conversationId != null)
            return RedirectToAction("Conversation", "Message", new { conversationId = conversationId });

        var conversationEntry = new ConversationEntity();
        await _conversationRepository.AddAsync(conversationEntry);
        await _conversationRepository.AddEntriesPersonalChatAsync(conversationEntry.Id, id1, userId);
        return RedirectToAction("Conversation", "Message", new { conversationId = conversationEntry.Id });
    }
    
    private async Task<List<UserEntity>> GetUsers(int page = 1, string filter = "", int pageSize = 10)
    {
        filter = filter.ToLower();
        return await _userRepository.GetPageAsync(page, pageSize,
            x => string.IsNullOrEmpty(filter) ||
                 (x.FirstName + " " + x.SecondName).StartsWith(filter, StringComparison.CurrentCultureIgnoreCase) ||
                 (x.SecondName + " " + x.FirstName).StartsWith(filter, StringComparison.CurrentCultureIgnoreCase));
    }
}

OVCHEGRAM/Views/ME/Conversations.cshtml
@model List<ConversationModel>

@{
    Layout = "_OvchegramLayout";
    var months = new Dictionary<int, string>
    {
        {1, "января"},
        {2, "февраля"},
        {3, "марта"},
        {4, "апреля"},
        {5, "мая"},
        {6, "июня"},
        {7, "июля"},
        {8, "августа"},
        {9, "сентября"},
        {10, "октября"},
        {11, "ноября"},
        {12, "декабря"}
    };
}

<link rel="stylesheet" href="~/css/ModalConversation.css"/>
<link rel="stylesheet" href="~/css/ChangeProfilePic.css"/>

<button id="openModalBtn" class="open-modal-btn">Создать беседу</button>

<div id="modalOverlay" class="modal-overlay">
    <div class="modal-content">
        <span class="close-modal">&times;</span>
        <input id="group-Title" placeholder="Введите название"/>
        <div id="addedUsers"></div>
        <input id="user-input" placeholder="Добавьте участников"/>
        <div id="user-list"></div>
        <div id="profileEditPic"></div>
        <label for="fileLoad">
            Изменить аватар
            <input type="file" name="File" id="fileLoad" accept="image/*" style="display: none"/>
        </label>
        <button id="confirm-btn">Создать беседу</button>
    </div>
</div>

@foreach (var conversation in @Model)
{
    var messageTime = conversation.LastMessageTime.Hour + ":" + (conversation.LastMessageTime.Minute > 9 ? "" : "0") + conversation.LastMessageTime.Minute;
    <a asp-controller="Message" asp-action="Conversation" asp-route-conversationId=@conversation.ConversationId>
        <div class="conversation">
            <img class="profilePic" src="@conversation.ConversationPictureName" alt="oi"/>
            <p class="conversationTitle">@conversation.ConversationTitle</p>
            <p class="conversationLastMessage">@conversation.LastMessageContent</p>
            <p class="conversationLastMessageTime">@conversation.LastMessageTime.Day @months[conversation.LastMessageTime.Month] @conversation.LastMessageTime.Year @messageTime</p>
            @if (conversation.HasNewMessages)
            {
                <div class="haveNewMessages"></div>
            }
        </div>
    </a>
    
}

<script src="~/js/Conversations.js"></script>
<script src="~/js/changeProfilePic.js"></script>

OVCHEGRAM/Views/ME/Profile.cshtml
@using System.Security.Claims
@model (UserProfileModel, bool)

@{
    Layout = "_OvchegramLayout";
    var user = Model.Item1;
    var isAllowed = Model.Item2;
}

<link rel="stylesheet" href="~/css/Profile.css"/>
<link rel="stylesheet" href="~/css/ChangeProfilePic.css"/>

<div class="text-center">
    <div id="userInfo">
        <img src="@user.FilePath" alt="oi" id="profilePic"></img>
        <h1 id="userName">@user.FirstName @user.SecondName</h1>
        <p id="userGender">@user.Gender</p>
        <p id="userTown">@user.Town</p>
        @if (isAllowed)
        {
            <button id="editBtn">Редактировать</button>
            <form>
                <button type="submit" asp-controller="ME" asp-action="LogOut">Выйти</button>
            </form>
        }
    </div>
    <div id="userEdit">
        <form asp-controller="ME" asp-action="ChangeProfile" method="post" enctype="multipart/form-data">
            <div id="profileEditPic">
                <img src="@user.FilePath" alt="oi" id="imgPreview">
            </div>
            <label for="fileLoad">
                Изменить аватар
                <input type="file" name="File" id="fileLoad" asp-for="Item1.File" accept="image/*" style="display: none"/>
            </label>
            <input name="FirstName" asp-for="Item1.FirstName"/>
            <input name="SecondName" asp-for="Item1.SecondName"/>
            <label class="col-form-label">
                Город
                <select name="town" id="citySelect" class="input-group-text" asp-for="Item1.Town">
                    <option selected>@user.Town</option>
                </select>
            </label>
            <label>
                <input type="radio" name="gender" value="Man" class="input-group-text" asp-for="Item1.Gender"> Man
                <input type="radio" name="gender" value="Woman" class="input-group-text" asp-for="Item1.Gender"> Woman
            </label>
            <button type="submit" id="saveBtn">Сохранить</button>
        </form>
        <button id="cancelBtn">Отменить</button>
    </div>
    
</div>

<script src="~/js/Profile.js"></script>
<script src="~/js/changeProfilePic.js"></script>
<script src="~/js/cities.js"></script>

OVCHEGRAM/Views/ME/Users.cshtml
@model IEnumerable<UserProfileModel>

@{
    Layout = "_OvchegramLayout";
}

<link rel="stylesheet" href="~/css/Users.css"/>

<input class="" type="text" id="filter"/>
<div id="items-container">
    <partial name="_PartialUsers" model="Model"/>
</div>

<div id="loading"></div>
<script src="~/js/Users.js"></script>